### ISSUE TITLE
Hide DB table row IDs from the public - UUIDs?

### ISSUE THREAD

**Issue by sventech** [JarrodCTaylor/authenticated-compojure-api#14]
It seems to be pretty common practice to hide implementation details like table row IDs from the public.

http://toddfredrich.com/ids-in-rest-api.html

Perhaps we could use a separate field of UUID / GUID to identify users, etc?

**Comment by JarrodCTaylor** [comment]
I will look into this enhancement sometime this week.

**Comment by JarrodCTaylor** [comment]
@sventech Are you aware of any disadvantage to using a UUID for the primary key of the users table? Or would there be an real advantage to making a separate UUID field in addition to the serial pk that is currently being used?

https://www.clever-cloud.com/blog/engineering/2015/05/20/why-auto-increment-is-a-terrible-idea/

**Comment by sventech** [comment]
It looks like Onyx does not support tables with non-numeric primary keys, though perhaps they could get the 128bit integer value of a UUIDv4.

https://github.com/onyx-platform/onyx-sql

I think the article you mentioned makes a compelling argument and UUIDv4 primary keys would be a good choice. All the arguments against UUID-as-key focused on performance, and PostgreSQL solves that handily.
