### ISSUE TITLE
Question about auth middleware

### ISSUE THREAD

**Issue by rcanepa** [JarrodCTaylor/authenticated-compojure-api#7]
Hey Jarrod, first of all, I wanted to say thank you for this amazing example. It covers a lot of important parts of a real application and I have been returning to it very often to learn how to resolve several issues.

However, I have doubts about why did you wrap the route with the wrap-authetication middleware, instead of defining it in the middlewares keyword like you did with the cors-mw. Here an example of what I am talking about:

```
    (wrap-authentication
     (DELETE* "/user/:id"  {:as request}
              :tags        ["User"]
              :path-params [id :- Long]
              :return      {:message String}
              :middlewares [cors-mw token-auth-mw]
              :summary     "Deletes the specified user. Requires token to have `admin` auth or self ID."
              :description "Authorization header expects the following format 'Token {token}'"
              (delete-user-response request id))
     token-backend)
```
Could be explained because you need to pass a parameter?

Also, in other cases, I saw that you repeated this along several routes instead of wrapping all of them through the context* macro, why is that?, can't it be done in that way?

**Comment by JarrodCTaylor** [comment]
Glad you are finding the project useful.

I have had reworking the middleware on my todo list for a while, but haven't made the time to do it.  I think that early on doing it that way was the path of least resistance and I never went back to refactor. I just pushed https://github.com/JarrodCTaylor/authenticated-compojure-api/commit/f81a5208d7c99371fa1ced62c9b86607fc4e9a6a  that refactors the handlers to  move the call to `wrap-authentication` inside the `middlewares` keyword. Thanks for pointing it out and motivating me to get it done.

I am unsure about your question related to the `context*` macro. As far as I know the context macro only provides a way of giving a common url prefix to a group of urls. https://github.com/weavejester/compojure/wiki/Nesting-routes so perhaps I misunderstanding what you are asking.

**Comment by yusup-a** [comment]
please keep up the good work. your work is helping me alot.

**Comment by rcanepa** [comment]
@JarrodCTaylor Glad you found motivation in my comment to keep working on this amazing tutorial!
Forget about my question about the context* macro, at that moment I wasn't aware of how it really works.

Anyway, thanks again for making this tutorial, which without doubts is one of the best tutorials available. Most of tutorials are focused in a specific part/module of an application and forget about code structure, testing, etc., but this one deals with all of that and more... it really resembles a real application.

**Comment by JarrodCTaylor** [comment]
Thanks for the kind words @yusup-a and @rcanepa.
