### ISSUE TITLE
update to compojure-api 1.0 API

### ISSUE THREAD

**Issue by sventech** [JarrodCTaylor/authenticated-compojure-api#8]
Change to new version of compojure-api for greater flexibility.

#### Move from compile-time to runtime route resolution.
- Most of the internal macro magic has been vaporized
- Uses internally (invokable) Records & Protocols, allowing easier integration to 3rd party libs like Liberator
  - even for large apps (100+ routes), route compilation takes now millis, instead of seconds
- sub-routes can be created with normal functions (or values), making it easier to:
  - pass in app-level dependencies from libs like Component
  - reuse shared request-handling time parameters like path-parameters and authorization info

More here https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md

**Comment by JarrodCTaylor** [comment]
It's on the TODO list. I will get things updated in the next week or so. I have a few other material changes I plan to make to the tests as well. Stay tuned.

**Comment by sventech** [comment]
Cool, I'm actually readying a pull request to implement it, but chatting with deraen about an issue I encountered. Have you chosen a license for this code? I'd really like to use it for a project.

**Comment by JarrodCTaylor** [comment]
A pull request is welcome. I tend to go with MIT license. I will get that added.

**Comment by JarrodCTaylor** [comment]
Closed with https://github.com/JarrodCTaylor/authenticated-compojure-api/pull/9
